---
sidebar: sidebar 
permalink: docs/hci_prereqs_deployment_configuration_restriction.html 
summary: Saiba mais sobre restrições de configuração de implantação. 
keywords: netapp, hci, deployment, restriction, configuration, nde, compute, node, storage 
---
= Restrições de configuração de implantação
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Certas configurações são restritas no mecanismo de implantação do NetApp, dependendo da versão do VMware vSphere, do tipo de nó de computação e do número de nós de storage. As configurações restritas se aplicam ao VMware vSphere 7,0 com H610C ou H615C nós de computação e dois ou três nós de storage. Se você quiser continuar com uma configuração restrita, selecione uma versão diferente do vSphere, como o vSphere 6,7, ou evite a implantação de nós de testemunha com um mínimo de quatro nós de storage na configuração.

Se você link:task_nde_select_inventory.html["Selecione uma configuração restrita na página *Inventário*"] durante a implantação, uma mensagem de erro será exibida com opções de configuração válidas alternativas.



== Encontre mais informações

https://docs.netapp.com/us-en/vcp/index.html["Plug-in do NetApp Element para vCenter Server"^]
