---
sidebar: sidebar 
permalink: docs/task_hcc_upgrade_element_software.html 
summary: Como parte de uma atualização do sistema NetApp HCI, você atualiza o software NetApp Element. 
keywords: netapp, hci, cluster, element, H610S upgrade, hcc 
---
= Atualize o software Element
:allow-uri-read: 


[role="lead"]
Para atualizar o software NetApp Element, você pode usar a IU ou a API REST do NetApp Hybrid Cloud Control. Certas operações são suprimidas durante uma atualização do software Element, como adicionar e remover nós, adicionar e remover unidades, e comandos associados a iniciadores, grupos de acesso de volume e redes virtuais, entre outros.


NOTE: A partir do Element 12,5, o NetApp HealthTools não é mais suportado para atualizações de software Element. Se você estiver executando o Element 11,0 ou 11,1, primeiro link:https://docs.netapp.com/us-en/hci19/docs/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools["Atualize para o Element 12,3 usando HealthTools"^] e depois atualize para o Element 12,5 ou posterior usando o Controle de nuvem híbrida da NetApp.

.O que você vai precisar
* *Admin Privileges*: Você tem permissões de administrador de cluster de armazenamento para executar a atualização.
* *Caminho de atualização válido*: Você verificou as informações do caminho de atualização para a versão do Element para a qual está atualizando e verificou que o caminho de atualização é válido. Consulte https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_is_the_upgrade_matrix_for_storage_clusters_running_NetApp_Element_software%3F["NetApp KB: Matriz de atualização para clusters de armazenamento que executam o software NetApp Element"^]
* *Sincronização da hora do sistema*: Você garantiu que a sincronização da hora do sistema em todos os nós e que o NTP está configurado corretamente para o cluster de armazenamento e nós. Cada nó deve ser configurado com um servidor de nomes DNS na IU da Web por nó (`https://[IP address]:442`) sem falhas de cluster não resolvidas relacionadas ao desvio de tempo.
* *Portas do sistema*: Se você estiver usando o Controle de nuvem híbrida da NetApp para atualizações, você garantiu que as portas necessárias estejam abertas. Consulte link:hci_prereqs_required_network_ports.html["Portas de rede"] para obter mais informações.
* *Nó de gerenciamento*: Para a API e a IU do NetApp Hybrid Cloud Control, o nó de gerenciamento em seu ambiente está executando a versão 11,3.
* *Serviços de gerenciamento*: Você atualizou seu pacote de serviços de gerenciamento para a versão mais recente.



IMPORTANT: Você deve atualizar para o pacote de serviços de gerenciamento mais recente antes de atualizar o software Element para a versão 12,5 ou posterior. Se você estiver atualizando o software Element para a versão 12,5 ou posterior, precisará dos serviços de gerenciamento 2.21.61 ou posterior para continuar.

* *Integridade do cluster*: Você verificou que o cluster está pronto para ser atualizado. link:task_hcc_upgrade_element_prechecks.html["Execute verificações de integridade do storage Element antes de atualizar o storage"]Consulte .
* * Controlador de gerenciamento de placa base (BMC) atualizado para H610S nós*: Você atualizou a versão do BMC para seus H610S nós. Consulte link:rn_H610S_BMC_3.84.07.html["notas de versão e instruções de atualização"].
* *Tempo de processo de atualização*: Você agendou tempo suficiente para realizar a atualização. Quando você atualiza para o software Element 12,5 ou posterior, o tempo do processo de atualização varia dependendo da versão atual do software Element e das atualizações de firmware.
+
[cols="20,20,20,20,20"]
|===
| Nó de storage | Versão atual do software Element | O tempo aproximado de instalação de software e firmware por nó 1 | O tempo aproximado de sincronização de dados por nó 2 | Tempo total aproximado de atualização por nó 


| Todos os nós da série H SolidFire e NetApp com firmware atualizado | 12.x | 15 minutos | 10 a 15 minutos | 20 a 30 minutos 


| H610S e H410S | 12.x e 11,8 | 60 minutos | 30 a 60 minutos | 90 a 120 minutos 


| H610S | 11,7 e anteriores | 90 minutos | 40 a 70 minutos | De 130 a 160 minutos, você também precisa https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["execute um desligamento completo do nó e desconexão de energia"^] para cada nó H610S. 
|===
+
1 para obter uma matriz completa de firmware e firmware de driver para o seu hardware, link:firmware_driver_versions.html["Versões de firmware e driver ESXi compatíveis para versões de NetApp HCI e firmware para nós de storage NetApp HCI"]consulte .

+
2 se você combinar um cluster com uma carga de IOPS de gravação pesada com um tempo de atualização de firmware mais longo, o tempo de sincronização de dados aumentará.

* *Contrato de Licença de Usuário final (EULA)*: Começando com os serviços de gerenciamento 2.20.69, você deve aceitar e salvar o EULA antes de usar a interface de usuário ou API do NetApp Hybrid Cloud Control para atualizar o software Element:
+
.. Abra o endereço IP do nó de gerenciamento em um navegador da Web:
+
[listing]
----
https://<ManagementNodeIP>
----
.. Faça login no controle de nuvem híbrida da NetApp fornecendo as credenciais de administrador do cluster de storage.
.. Selecione *Upgrade* perto do canto superior direito da interface.
.. O EULA aparece. Role para baixo, selecione *Aceito para atualizações atuais e futuras* e selecione *Salvar*.




.Opções de atualização
Escolha uma das seguintes opções de atualização do software Element:

* <<Use a IU do Controle de nuvem híbrida da NetApp para atualizar o storage Element>>
* <<Use a API de controle de nuvem híbrida da NetApp para atualizar o storage Element>>



IMPORTANT: Se você estiver atualizando um nó da série H610S para o elemento 12,5 ou posterior e o nó estiver executando uma versão do software Element anterior a 11,8, será necessário executar as etapas de atualização adicionais https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Artigo da KB"^] para cada nó de storage. Se você estiver executando o Element 11,8 ou posterior, as etapas adicionais de atualização não serão necessárias.



== Use a IU do Controle de nuvem híbrida da NetApp para atualizar o storage Element

Usando a IU do Controle de nuvem híbrida da NetApp, você pode atualizar um cluster de storage.


CAUTION: Para possíveis problemas durante a atualização dos clusters de storage usando o Controle de nuvem híbrida da NetApp e suas soluções alternativas, consulte este https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Potential_issues_and_workarounds_when_running_storage_upgrades_using_NetApp_Hybrid_Cloud_Control["Artigo da KB"^].

.Passos
. Abra o endereço IP do nó de gerenciamento em um navegador da Web:
+
[listing]
----
https://<ManagementNodeIP>
----
. Faça login no controle de nuvem híbrida da NetApp fornecendo as credenciais de administrador do cluster de storage.
. Selecione *Upgrade* perto do canto superior direito da interface.
. Na página *Upgrades*, selecione *Storage*.
+
A guia *Storage* lista os clusters de armazenamento que fazem parte da sua instalação. Se um cluster estiver inacessível pelo Controle de nuvem híbrida da NetApp, ele não será exibido na página *Upgrades*.

. Escolha entre as opções a seguir e execute o conjunto de etapas aplicáveis ao cluster:
+
[cols="2*"]
|===
| Opção | Passos 


| Todos os clusters executando o elemento 11,8 e posterior  a| 
.. Selecione *Procurar* para carregar o pacote de atualização que transferiu.
.. Aguarde até que o upload seja concluído. Uma barra de progresso mostra o status do upload.
+

CAUTION: O upload do arquivo será perdido se você navegar para longe da janela do navegador.

+
É apresentada uma mensagem no ecrã depois de o ficheiro ser carregado e validado com êxito. A validação pode demorar vários minutos. Se você navegar para longe da janela do navegador nesta fase, o upload do arquivo será preservado.

.. Selecione *Begin Upgrade*.
+

TIP: O *Status do Upgrade* muda durante a atualização para refletir o status do processo. Ele também muda em resposta às ações que você toma, como pausar a atualização, ou se a atualização retornar um erro. <<Alterações de status da atualização>>Consulte .

+

NOTE: Enquanto a atualização estiver em andamento, você pode sair da página e voltar a ela mais tarde para continuar monitorando o progresso. A página não atualiza dinamicamente o status e a versão atual se a linha do cluster for recolhida. A linha do cluster deve ser expandida para atualizar a tabela ou você pode atualizar a página.

+
Pode transferir registos após a conclusão da atualização.





| Você está atualizando um cluster H610S executando a versão do Element anterior a 11,8.  a| 
.. Selecione a seta suspensa ao lado do cluster que você está atualizando e selecione a partir das versões de atualização disponíveis.
.. Selecione *Begin Upgrade*. Após a conclusão da atualização, a IU solicitará que você execute etapas adicionais de atualização.
.. Conclua as etapas adicionais necessárias no https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Artigo da KB"^] e confirme na IU que você as concluiu.


Pode transferir registos após a conclusão da atualização. Para obter informações sobre as várias alterações de status de atualização, <<Alterações de status da atualização>>consulte .

|===




=== Alterações de status da atualização

Aqui estão os diferentes estados que a coluna *Status da atualização* na IU mostra antes, durante e após o processo de atualização:

[cols="2*"]
|===
| Estado de atualização | Descrição 


| Atualizado | O cluster foi atualizado para a versão mais recente do Element disponível. 


| Versões disponíveis | Versões mais recentes do Element e/ou firmware de storage estão disponíveis para atualização. 


| Em curso | A atualização está em andamento. Uma barra de progresso mostra o status da atualização. As mensagens na tela também mostram falhas no nível do nó e exibem a ID do nó de cada nó no cluster à medida que a atualização progride. Você pode monitorar o status de cada nó usando a IU do Element ou o plug-in do NetApp Element para a IU do vCenter Server. 


| Atualizar Pausando | Você pode optar por pausar a atualização. Dependendo do estado do processo de atualização, a operação de pausa pode ser bem-sucedida ou falhar. Você verá um prompt da interface do usuário solicitando que você confirme a operação de pausa. Para garantir que o cluster esteja em um local seguro antes de pausar uma atualização, pode levar até duas horas para que a operação de atualização seja completamente pausada. Para retomar a atualização, selecione *Resume*. 


| Em pausa | Fez uma pausa na atualização. Selecione *Resume* para retomar o processo. 


| Erro | Ocorreu um erro durante a atualização. Você pode baixar o log de erros e enviá-lo para o suporte da NetApp. Depois de resolver o erro, você pode retornar à página e selecionar *Resume*. Quando você retoma a atualização, a barra de progresso recua por alguns minutos enquanto o sistema executa a verificação de integridade e verifica o estado atual da atualização. 


| Completo com acompanhamento | Somente para nós H610S atualizando a partir da versão do Element anterior à 11,8. Após a conclusão da fase 1 do processo de atualização, este estado solicita que você execute etapas adicionais de atualização (consulte a https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Artigo da KB"^] ). Depois de concluir estes passos adicionais e confirmar que o concluiu, o estado muda para *até à data*. 
|===


== Use a API de controle de nuvem híbrida da NetApp para atualizar o storage Element

Você pode usar APIs para atualizar nós de storage em um cluster para a versão mais recente do software Element. Você pode usar uma ferramenta de automação de sua escolha para executar as APIs. O fluxo de trabalho da API documentado aqui usa a IU da API REST disponível no nó de gerenciamento como exemplo.

.Passos
. Faça download do pacote de atualização de storage para um dispositivo que esteja acessível ao nó de gerenciamento; vá para o software NetApp HCI https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab["página de transferências"^] e baixe a imagem mais recente do nó de storage.
. Faça o upload do pacote de atualização de armazenamento para o nó de gerenciamento:
+
.. Abra a IU da API REST do nó de gerenciamento no nó de gerenciamento:
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
.. Selecione *autorizar* e preencha o seguinte:
+
... Introduza o nome de utilizador e a palavra-passe do cluster.
... Introduza a ID do cliente como `mnode-client`.
... Selecione *autorizar* para iniciar uma sessão.
... Feche a janela autorização.


.. Na IU da API REST, selecione *POST /packages*.
.. Selecione *Experimente*.
.. Selecione *Procurar* e selecione o pacote de atualização.
.. Selecione *execute* para iniciar o upload.
.. Na resposta, copie e salve o ID do (`"id"`pacote ) para uso em uma etapa posterior.


. Verifique o status do upload.
+
.. Na IU da API REST, selecione *GET​ /packages​/​ id/status*.
.. Selecione *Experimente*.
.. Insira o ID do pacote que você copiou na etapa anterior em *id*.
.. Selecione *execute* para iniciar a solicitação de status.
+
A resposta indica `state` como `SUCCESS` quando concluída.



. Localize a ID do cluster de armazenamento:
+
.. Abra a IU da API REST do nó de gerenciamento no nó de gerenciamento:
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. Selecione *autorizar* e preencha o seguinte:
+
... Introduza o nome de utilizador e a palavra-passe do cluster.
... Introduza a ID do cliente como `mnode-client`.
... Selecione *autorizar* para iniciar uma sessão.
... Feche a janela autorização.


.. Na IU da API REST, selecione *GET /installations*.
.. Selecione *Experimente*.
.. Selecione *Executar*.
.. Na resposta, copie o ID do ativo de instalação (`"id"`).
.. Na IU da API REST, selecione *GET /installations/
.. Selecione *Experimente*.
.. Cole o ID do ativo de instalação no campo *id*.
.. Selecione *Executar*.
.. A partir da resposta, copie e salve o ID do cluster de armazenamento (`"id"`) do cluster que pretende atualizar para uso em uma etapa posterior.


. Execute a atualização de armazenamento:
+
.. Abra a IU da API REST de storage no nó de gerenciamento:
+
[listing]
----
https://<ManagementNodeIP>/storage/1/
----
.. Selecione *autorizar* e preencha o seguinte:
+
... Introduza o nome de utilizador e a palavra-passe do cluster.
... Introduza a ID do cliente como `mnode-client`.
... Selecione *autorizar* para iniciar uma sessão.
... Feche a janela autorização.


.. Selecione *POST /Upgrades*.
.. Selecione *Experimente*.
.. Introduza a ID do pacote de atualização no campo Parameter (parâmetro).
.. Introduza a ID do cluster de armazenamento no campo Parameter (parâmetro).
+
A carga útil deve ser semelhante ao seguinte exemplo:

+
[listing]
----
{
  "config": {},
  "packageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4",
  "storageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4"
}
----
.. Selecione *execute* para iniciar a atualização.
+
A resposta deve indicar o estado como `initializing`:

+
[listing]
----
{
  "_links": {
    "collection": "https://localhost:442/storage/upgrades",
    "self": "https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1",
    "log": https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1/log
  },
  "storageId": "114f14a4-1a1a-11e9-9088-6c0b84e200b4",
  "upgradeId": "334f14a4-1a1a-11e9-1055`-6c0b84e2001b4",
  "packageId": "774f14a4-1a1a-11e9-8888-6c0b84e200b4",
  "config": {},
  "state": "initializing",
  "status": {
    "availableActions": [
      "string"
    ],
    "message": "string",
    "nodeDetails": [
      {
        "message": "string",
        "step": "NodePreStart",
        "nodeID": 0,
        "numAttempt": 0
      }
    ],
    "percent": 0,
    "step": "ClusterPreStart",
    "timestamp": "2020-04-21T22:10:57.057Z",
    "failedHealthChecks": [
      {
        "checkID": 0,
        "name": "string",
        "displayName": "string",
        "passed": true,
        "kb": "string",
        "description": "string",
        "remedy": "string",
        "severity": "string",
        "data": {},
        "nodeID": 0
      }
    ]
  },
  "taskId": "123f14a4-1a1a-11e9-7777-6c0b84e123b2",
  "dateCompleted": "2020-04-21T22:10:57.057Z",
  "dateCreated": "2020-04-21T22:10:57.057Z"
}
----
.. Copie o ID de atualização (`"upgradeId"`) que faz parte da resposta.


. Verifique o progresso e os resultados da atualização:
+
.. Selecione *GET ​/Upgrades/
.. Selecione *Experimente*.
.. Insira o ID de atualização da etapa anterior em *upgradeId*.
.. Selecione *Executar*.
.. Siga um destes procedimentos se houver problemas ou requisitos especiais durante a atualização:
+
[cols="2*"]
|===
| Opção | Passos 


| Você precisa corrigir problemas de integridade do cluster devido a `failedHealthChecks` mensagem no corpo de resposta.  a| 
... Vá para o artigo específico da KB listado para cada problema ou execute o recurso especificado.
... Se um KB for especificado, conclua o processo descrito no artigo da KB relevante.
... Depois de resolver problemas de cluster, reautentique se necessário e selecione *put ​/Upgrades/
... Selecione *Experimente*.
... Insira o ID de atualização da etapa anterior em *upgradeId*.
... Introduza `"action":"resume"` o corpo do pedido.
+
[listing]
----
{
  "action": "resume"
}
----
... Selecione *Executar*.




| Você precisa pausar a atualização porque a janela de manutenção está fechando ou por outro motivo.  a| 
... Reautentique se necessário e selecione *put ​/Upgrades/
... Selecione *Experimente*.
... Insira o ID de atualização da etapa anterior em *upgradeId*.
... Introduza `"action":"pause"` o corpo do pedido.
+
[listing]
----
{
  "action": "pause"
}
----
... Selecione *Executar*.




| Se você estiver atualizando um cluster H610S executando uma versão do Element anterior a 11,8, verá o estado `finishedNeedsAck` no corpo da resposta. Você deve executar etapas de atualização adicionais para cada nó de storage do H610S.  a| 
... Conclua as etapas adicionais de atualização https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["Artigo da KB"^] para cada nó.
... Reautentique se necessário e selecione *put ​/Upgrades/
... Selecione *Experimente*.
... Insira o ID de atualização da etapa anterior em *upgradeId*.
... Introduza `"action":"acknowledge"` o corpo do pedido.
+
[listing]
----
{
  "action": "acknowledge"
}
----
... Selecione *Executar*.


|===
.. Execute a API *GET ​/Upgrades/"upgradeId"* várias vezes, conforme necessário, até que o processo esteja concluído.
+
Durante a atualização, o `status` indica `running` se não foram encontrados erros. À medida que cada nó é atualizado, o `step` valor muda para `NodeFinished`.

+
A atualização foi concluída com êxito quando o `percent` valor é `100` e o `state` indica `finished`.







== O que acontece se uma atualização falhar usando o controle de nuvem híbrida da NetApp

Se uma unidade ou nó falhar durante uma atualização, a IU do Element mostrará falhas de cluster. O processo de atualização não avança para o nó seguinte e aguarda a resolução das falhas do cluster. A barra de progresso na IU mostra que a atualização está aguardando a resolução das falhas do cluster. Nesta fase, selecionar *Pausa* na IU não funcionará, porque a atualização aguarda que o cluster esteja saudável. Você precisará ativar o suporte da NetApp para ajudar na investigação de falha.

O controle de nuvem híbrida da NetApp tem um período de espera pré-definido de três horas, durante o qual um dos seguintes cenários pode acontecer:

* As falhas do cluster são resolvidas dentro da janela de três horas e a atualização é retomada. Você não precisa tomar nenhuma ação nesse cenário.
* O problema persiste após três horas e o status da atualização mostra *erro* com um banner vermelho. Você pode retomar a atualização selecionando *Resume* após o problema ser resolvido.
* O suporte da NetApp determinou que a atualização precisa ser temporariamente cancelada para tomar medidas corretivas antes da janela de três horas. O suporte usará a API para cancelar a atualização.



CAUTION: Abortar a atualização do cluster enquanto um nó está sendo atualizado pode resultar na remoção desgraciosa das unidades do nó. Se as unidades forem removidas sem graça, adicionar as unidades de volta durante uma atualização exigirá intervenção manual pelo suporte da NetApp. O nó pode estar demorando mais para fazer atualizações de firmware ou atividades de sincronização pós-atualização. Se o progresso da atualização parecer interrompido, entre em Contato com o suporte da NetApp para obter assistência.

[discrete]
== Encontre mais informações

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in do NetApp Element para vCenter Server"^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/["Página de recursos do NetApp HCI"^]

